# Generated by Django 3.2.9 on 2021-12-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField(max_length=500)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_modifica', models.DateField(null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
