# Generated by Django 3.2.9 on 2022-01-29 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlBultos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('observacion', models.TextField()),
                ('estado', models.BooleanField(default=True)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='curacion.finca')),
            ],
        ),
        migrations.CreateModel(
            name='ControlBultosDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilon', models.IntegerField()),
                ('libras', models.DecimalField(decimal_places=2, max_digits=5)),
                ('clase', models.CharField(max_length=100)),
                ('corte', models.CharField(max_length=100)),
                ('bulto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='curacion.controlbultos')),
            ],
        ),
    ]
