# Generated by Django 3.2.9 on 2022-03-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curacion', '0003_pilon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlbultos',
            name='observacion',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
