# Generated by Django 3.2.9 on 2022-03-16 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curacion', '0005_auto_20220314_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='controlbultosdetalle',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='curacion.clase'),
        ),
        migrations.AlterField(
            model_name='controlbultosdetalle',
            name='corte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='curacion.corte'),
        ),
    ]
