# Generated by Django 3.2.9 on 2022-03-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curacion', '0006_auto_20220316_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
