# Generated by Django 3.2.9 on 2022-03-23 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curacion', '0007_variedad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlbultosdetalle',
            name='pilon',
        ),
        migrations.AddField(
            model_name='controlbultos',
            name='condicion',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='controlbultos',
            name='pilon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='curacion.pilon'),
        ),
    ]
