# Generated by Django 3.2.9 on 2022-05-26 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curacion', '0012_variedad_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlTemperaturaBultos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('ciclo', models.IntegerField()),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('estado', models.BooleanField(default=True)),
                ('bulto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='curacion.controlbultos')),
                ('corte', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='curacion.corte')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='curacion.finca')),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='curacion.variedad')),
            ],
        ),
    ]
