# Generated by Django 3.2.9 on 2022-05-31 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curacion', '0013_controltemperaturabultos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controltemperaturabultos',
            name='temperatura',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
